# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EurostatDownloader
                                 A QGIS plugin
 This plugin can be used to join data from the Eurostat API with a local vector layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-28
        copyright            : (C) 2023 by Cuvuliuc Alex-Andrei
        email                : cuvuliucalexandrei@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys
import site
import pkg_resources
import platform

DEPENDENCIES_FOLDER = 'deps'

def pre_init_plugin():
    extra_libs_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), DEPENDENCIES_FOLDER)
    )
    # add to python path
    site.addsitedir(extra_libs_path)
    # pkg_resources doesn't listen to changes on sys.path.
    pkg_resources.working_set.add_entry(extra_libs_path)

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EurostatDownloader class from file EurostatDownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    pre_init_plugin()
    from .eurostat_downloader import EurostatDownloader
    return EurostatDownloader(iface)
