[mypy]
ignore_missing_imports = true
disallow_any_explicit = True
strict = true
exclude = (^eurostat_downloader/ui/|^eurostat_downloader/src/ui/|^eurostat_downloader/resources(_rc)?\.py$)

[mypy-eurostat_downloader.ui.*]
ignore_errors = true

[mypy-eurostat_downloader.src.ui.*]
ignore_errors = true

[mypy-eurostat_downloader.resources]
ignore_errors = true

[mypy-eurostat_downloader.resources_rc]
ignore_errors = true
