[tool.qgis_plugin_dev_tools]
plugin_package_name = "eurostat_downloader"
runtime_requires = [
    "eurostat",
    "attrs",
]
auto_add_recursive_runtime_dependencies = true
version_number_source = "changelog"
