# Form implementation generated from reading ui file 'eurostat_downloader/ui/gisco_join_report.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_GISCOJoinReport(object):
    def setupUi(self, GISCOJoinReport):
        GISCOJoinReport.setObjectName("GISCOJoinReport")
        GISCOJoinReport.resize(779, 645)
        self.gridLayout = QtWidgets.QGridLayout(GISCOJoinReport)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetGISCOJoinReport = QtWidgets.QTableWidget(parent=GISCOJoinReport)
        self.tableWidgetGISCOJoinReport.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.tableWidgetGISCOJoinReport.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.tableWidgetGISCOJoinReport.setObjectName("tableWidgetGISCOJoinReport")
        self.tableWidgetGISCOJoinReport.setColumnCount(0)
        self.tableWidgetGISCOJoinReport.setRowCount(0)
        self.tableWidgetGISCOJoinReport.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetGISCOJoinReport.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidgetGISCOJoinReport, 0, 0, 1, 1)

        self.retranslateUi(GISCOJoinReport)
        QtCore.QMetaObject.connectSlotsByName(GISCOJoinReport)

    def retranslateUi(self, GISCOJoinReport):
        _translate = QtCore.QCoreApplication.translate
        GISCOJoinReport.setWindowTitle(_translate("GISCOJoinReport", "Join report"))
        self.tableWidgetGISCOJoinReport.setSortingEnabled(True)
