# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/Desktop/qgis_plugins/eurostat_downloader/ui/gisco_join_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GISCOJoinReport(object):
    def setupUi(self, GISCOJoinReport):
        GISCOJoinReport.setObjectName("GISCOJoinReport")
        GISCOJoinReport.resize(779, 645)
        self.gridLayout = QtWidgets.QGridLayout(GISCOJoinReport)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetGISCOJoinReport = QtWidgets.QTableWidget(GISCOJoinReport)
        self.tableWidgetGISCOJoinReport.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidgetGISCOJoinReport.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidgetGISCOJoinReport.setObjectName("tableWidgetGISCOJoinReport")
        self.tableWidgetGISCOJoinReport.setColumnCount(0)
        self.tableWidgetGISCOJoinReport.setRowCount(0)
        self.tableWidgetGISCOJoinReport.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetGISCOJoinReport.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidgetGISCOJoinReport, 0, 0, 1, 1)

        self.retranslateUi(GISCOJoinReport)
        QtCore.QMetaObject.connectSlotsByName(GISCOJoinReport)

    def retranslateUi(self, GISCOJoinReport):
        _translate = QtCore.QCoreApplication.translate
        GISCOJoinReport.setWindowTitle(_translate("GISCOJoinReport", "Join report"))
        self.tableWidgetGISCOJoinReport.setSortingEnabled(True)
