# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/Desktop/qgis_plugins/eurostat_downloader/ui/section_dialog_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimePeriodDialog(object):
    def setupUi(self, TimePeriodDialog):
        TimePeriodDialog.setObjectName("TimePeriodDialog")
        TimePeriodDialog.resize(440, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TimePeriodDialog.sizePolicy().hasHeightForWidth())
        TimePeriodDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimePeriodDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameStart = QtWidgets.QFrame(TimePeriodDialog)
        self.frameStart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStart.setObjectName("frameStart")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameStart)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelStart = QtWidgets.QLabel(self.frameStart)
        self.labelStart.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelStart.setObjectName("labelStart")
        self.verticalLayout_2.addWidget(self.labelStart)
        self.verticalLayout.addWidget(self.frameStart)
        self.frameEnd = QtWidgets.QFrame(TimePeriodDialog)
        self.frameEnd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEnd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEnd.setObjectName("frameEnd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameEnd)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelEnd = QtWidgets.QLabel(self.frameEnd)
        self.labelEnd.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelEnd.setObjectName("labelEnd")
        self.verticalLayout_3.addWidget(self.labelEnd)
        self.verticalLayout.addWidget(self.frameEnd)
        self.buttonReset = QtWidgets.QPushButton(TimePeriodDialog)
        self.buttonReset.setObjectName("buttonReset")
        self.verticalLayout.addWidget(self.buttonReset)

        self.retranslateUi(TimePeriodDialog)
        QtCore.QMetaObject.connectSlotsByName(TimePeriodDialog)

    def retranslateUi(self, TimePeriodDialog):
        _translate = QtCore.QCoreApplication.translate
        TimePeriodDialog.setWindowTitle(_translate("TimePeriodDialog", "Form"))
        self.labelStart.setText(_translate("TimePeriodDialog", "Select start time"))
        self.labelEnd.setText(_translate("TimePeriodDialog", "Select end time"))
        self.buttonReset.setText(_translate("TimePeriodDialog", "Reset values"))
