# Form implementation generated from reading ui file 'eurostat_downloader/ui/settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(516, 218)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SettingsDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=SettingsDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxAgencyEUROSTAT = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxAgencyEUROSTAT.setChecked(True)
        self.checkBoxAgencyEUROSTAT.setObjectName("checkBoxAgencyEUROSTAT")
        self.verticalLayout.addWidget(self.checkBoxAgencyEUROSTAT)
        self.checkBoxAgencyCOMEXT = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxAgencyCOMEXT.setChecked(True)
        self.checkBoxAgencyCOMEXT.setObjectName("checkBoxAgencyCOMEXT")
        self.verticalLayout.addWidget(self.checkBoxAgencyCOMEXT)
        self.checkBoxAgencyCOMP = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxAgencyCOMP.setChecked(True)
        self.checkBoxAgencyCOMP.setObjectName("checkBoxAgencyCOMP")
        self.verticalLayout.addWidget(self.checkBoxAgencyCOMP)
        self.checkBoxAgencyEMPL = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxAgencyEMPL.setChecked(True)
        self.checkBoxAgencyEMPL.setObjectName("checkBoxAgencyEMPL")
        self.verticalLayout.addWidget(self.checkBoxAgencyEMPL)
        self.checkBoxAgencyGROW = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxAgencyGROW.setChecked(True)
        self.checkBoxAgencyGROW.setObjectName("checkBoxAgencyGROW")
        self.verticalLayout.addWidget(self.checkBoxAgencyGROW)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label.setText(_translate("SettingsDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Agencies</span></p></body></html>"))
        self.checkBoxAgencyEUROSTAT.setText(_translate("SettingsDialog", "EUROSTAT"))
        self.checkBoxAgencyCOMEXT.setText(_translate("SettingsDialog", "COMEXT"))
        self.checkBoxAgencyCOMP.setText(_translate("SettingsDialog", "COMP"))
        self.checkBoxAgencyEMPL.setText(_translate("SettingsDialog", "EMPL"))
        self.checkBoxAgencyGROW.setText(_translate("SettingsDialog", "GROW"))
