# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/alex/alex/python-modules-packages-utils/QGIS_plugins/eurostat_downloader/ui/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName('SettingsDialog')
        SettingsDialog.resize(516, 517)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SettingsDialog)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.frame = QtWidgets.QFrame(SettingsDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName('frame')
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName('gridLayout')
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName('verticalLayout_11')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName('label_2')
        self.verticalLayout_3.addWidget(self.label_2)
        self.checkBoxVerifySSL = QtWidgets.QCheckBox(self.frame)
        self.checkBoxVerifySSL.setChecked(True)
        self.checkBoxVerifySSL.setObjectName('checkBoxVerifySSL')
        self.verticalLayout_3.addWidget(self.checkBoxVerifySSL)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName('verticalLayout_10')
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName('label_3')
        self.verticalLayout_10.addWidget(self.label_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName('verticalLayout_9')
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName('verticalLayout_5')
        self.labelProxyHost = QtWidgets.QLabel(self.frame)
        self.labelProxyHost.setObjectName('labelProxyHost')
        self.verticalLayout_5.addWidget(self.labelProxyHost)
        self.lineEditProxyHost = QtWidgets.QLineEdit(self.frame)
        self.lineEditProxyHost.setObjectName('lineEditProxyHost')
        self.verticalLayout_5.addWidget(self.lineEditProxyHost)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.labelProxyPort = QtWidgets.QLabel(self.frame)
        self.labelProxyPort.setObjectName('labelProxyPort')
        self.verticalLayout_4.addWidget(self.labelProxyPort)
        self.lineEditProxyPort = QtWidgets.QLineEdit(self.frame)
        self.lineEditProxyPort.setObjectName('lineEditProxyPort')
        self.verticalLayout_4.addWidget(self.lineEditProxyPort)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName('verticalLayout_6')
        self.labelProxyUser = QtWidgets.QLabel(self.frame)
        self.labelProxyUser.setObjectName('labelProxyUser')
        self.verticalLayout_6.addWidget(self.labelProxyUser)
        self.lineEditProxyUser = QtWidgets.QLineEdit(self.frame)
        self.lineEditProxyUser.setObjectName('lineEditProxyUser')
        self.verticalLayout_6.addWidget(self.lineEditProxyUser)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName('verticalLayout_7')
        self.labelProxyPassword = QtWidgets.QLabel(self.frame)
        self.labelProxyPassword.setObjectName('labelProxyPassword')
        self.verticalLayout_7.addWidget(self.labelProxyPassword)
        self.lineEditProxyPassword = QtWidgets.QLineEdit(self.frame)
        self.lineEditProxyPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditProxyPassword.setObjectName('lineEditProxyPassword')
        self.verticalLayout_7.addWidget(self.lineEditProxyPassword)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName('label')
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName('verticalLayout')
        self.checkBoxAgencyEUROSTAT = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAgencyEUROSTAT.setChecked(True)
        self.checkBoxAgencyEUROSTAT.setObjectName('checkBoxAgencyEUROSTAT')
        self.verticalLayout.addWidget(self.checkBoxAgencyEUROSTAT)
        self.checkBoxAgencyCOMEXT = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAgencyCOMEXT.setChecked(True)
        self.checkBoxAgencyCOMEXT.setObjectName('checkBoxAgencyCOMEXT')
        self.verticalLayout.addWidget(self.checkBoxAgencyCOMEXT)
        self.checkBoxAgencyCOMP = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAgencyCOMP.setChecked(True)
        self.checkBoxAgencyCOMP.setObjectName('checkBoxAgencyCOMP')
        self.verticalLayout.addWidget(self.checkBoxAgencyCOMP)
        self.checkBoxAgencyEMPL = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAgencyEMPL.setChecked(True)
        self.checkBoxAgencyEMPL.setObjectName('checkBoxAgencyEMPL')
        self.verticalLayout.addWidget(self.checkBoxAgencyEMPL)
        self.checkBoxAgencyGROW = QtWidgets.QCheckBox(self.frame)
        self.checkBoxAgencyGROW.setChecked(True)
        self.checkBoxAgencyGROW.setObjectName('checkBoxAgencyGROW')
        self.verticalLayout.addWidget(self.checkBoxAgencyGROW)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName('buttonBox')
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(SettingsDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate('SettingsDialog', 'Settings'))
        self.label_2.setText(
            _translate(
                'SettingsDialog',
                '<html><head/><body><p><span style=" font-size:12pt; font-weight:600;">Connection</span></p></body></html>',
            )
        )
        self.checkBoxVerifySSL.setText(
            _translate('SettingsDialog', 'Verify SSL')
        )
        self.label_3.setText(
            _translate(
                'SettingsDialog',
                '<html><head/><body><p><span style=" font-weight:600;">Proxy (defaults to QGIS settings)</span></p></body></html>',
            )
        )
        self.labelProxyHost.setText(_translate('SettingsDialog', 'Host'))
        self.labelProxyPort.setText(_translate('SettingsDialog', 'Port'))
        self.labelProxyUser.setText(_translate('SettingsDialog', 'User'))
        self.labelProxyPassword.setText(
            _translate('SettingsDialog', 'Password')
        )
        self.label.setText(
            _translate(
                'SettingsDialog',
                '<html><head/><body><p><span style=" font-size:12pt; font-weight:600;">Agencies</span></p></body></html>',
            )
        )
        self.checkBoxAgencyEUROSTAT.setText(
            _translate('SettingsDialog', 'EUROSTAT')
        )
        self.checkBoxAgencyCOMEXT.setText(
            _translate('SettingsDialog', 'COMEXT')
        )
        self.checkBoxAgencyCOMP.setText(_translate('SettingsDialog', 'COMP'))
        self.checkBoxAgencyEMPL.setText(_translate('SettingsDialog', 'EMPL'))
        self.checkBoxAgencyGROW.setText(_translate('SettingsDialog', 'GROW'))
